### ISSUE TITLE
TypeError: Meteor.publishWithRedis is not a function!

### ISSUE THREAD

**Issue by thearabbit** [cult-of-coders/redis-oplog#93]
get error `TypeError: Meteor.publishWithRedis is not a function`
```js
// redis.js
// in startup server file (ex: /imports/startup/server/redis.js)
import {RedisOplog} from 'meteor/cultofcoders:redis-oplog';

// simple usage
RedisOplog.init() // will work with 127.0.0.1:6379, the default

// sets up the configuration parameters:
// https://github.com/luin/ioredis#connect-to-redis
RedisOplog.init({
    redis: {
        port: 6379,          // Redis port
        host: '127.0.0.1',   // Redis host
    },
    debug: false, // default is false,
    overridePublishFunction: false // replaces .publish with .publishWithRedis, leave false if you don't want to override it
});
------------------------------
// server
Meteor.publishWithRedis('links.all', function () {
    return Links.find();
    // you can also return an array of cursors
});
```

**Comment by thearabbit** [comment]
Should I install `redis` first?

**Comment by theodorDiaconu** [comment]
redis.js needs to be loaded as first thing, in your case you call publishWithRedis before RedisOplog.init(). yes, install redis as well.

**Comment by thearabbit** [comment]
Thanks for your reply, I will try.
